spring:
    pulsar:
      client:
#        service-url: pulsar+ssl://sn-academy.sndevadvocate.snio.cloud:6651
#        auth-plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
#        authentication:
#          issuer-url: https://auth.streamnative.cloud/
#          private-key: file:///Users/tspann/Downloads/sndevadvocate-tspann.json
#          audience: urn:sn:pulsar:sndevadvocate:my-instance
#        service-url: pulsar://72.82.137.252:6650
        service-url: pulsar://pulsar1:6650
      producer:
        batching-enabled: false
        send-timeout-ms: 90000
        producer-name: gtfsrtspringboot
        topic-name: persistent://public/default/gtfsrealtime

api:
  mtaalerts-url: http://gtfsrt.prod.obanyc.com/alerts?key=
  vehiclepositions-url: http://gtfsrt.prod.obanyc.com/vehiclePositions?key=
  tripupdates-url: http://gtfsrt.prod.obanyc.com/tripUpdates?key=
  key: ${GTFS_KEY:}

logging:
  level:
    org.apache.pulsar: error
    root: info
    ROOT: info
    dev.datainmotion.gtfsrealtime: info

server.port: 8799
